### ISSUE TITLE
Homebridge Support - HomeKit (Event Polling)

### ISSUE THREAD

**Issue by Andybishop** [Tristan79/iBrew#16]
I followed the instructions, but I am still unable to get the Python scripts to run and communicate with the Kettle, I have done the following.

I have the scripts on my ubuntu box, ran the following:-

sudo apt install python-pip
pip install --download=/tmp -r requirements.txt
pip install --user --no-index --find-links=/tmp -r requirements.txt

if I run Python iBrew, I can see the list of commands but can't get any of them to work...

I get the following when trying to tell it what the IP of the iKettle 2.0 is...

python ibrew host 192.168.1.52

  Starting please wait...

Traceback (most recent call last):
  File "/home/andy/iBrew/smarter/SmarterProtocol.py", line 686, in code_to_number
    return int(code,16)
ValueError: invalid literal for int() with base 16: 'ho'

Could not convert code to number: ho
Could not encode code 'host' at position: 1
Traceback (most recent call last):
  File "/home/andy/iBrew/smarter/SmarterProtocol.py", line 745, in codes_to_message
    message += self.code_to_raw(code[i_2]+code[i_2+1])
  File "/home/andy/iBrew/smarter/SmarterProtocol.py", line 681, in code_to_raw
    return self.number_to_raw(self.code_to_number(code))
  File "/home/andy/iBrew/smarter/SmarterProtocol.py", line 688, in code_to_number
    raise SmarterError(ConvertCodeNumber,"Could not convert code to number: " + code )
SmarterError

iBrew: Sending raw command message failed

**Comment by Tristan79** [comment]
You definitely found a bug. (and I found two more :-) Luckily its in a part you do not need.
You do not need the host parameter:

Try: 

python ibrew start 192.168.1.52

which uses the default settings

python ibrew heat 80 192.168.1.52

Boil water 'till 80 degrees celcius...

python ibrew stop 192.168.1.52

Stop the boiling.

**Comment by Andybishop** [comment]
Hi,  Thats great, thanks for your help, those commands work great, I just need to figure out how to call them from Homebridge, had a quick go with cmdswitch2 but accessory didn't show up after editing the config.json to call the commands above.

**Comment by Tristan79** [comment]
I have not tried homebridge, (i uses the voice recognition build in osx), because I can not rely on my internet connection. If you figure it out please before sunday, post it here. :-)

**Comment by Andybishop** [comment]
Hi, Had a bit more time to give this a try, and I have kind of got it working with Homebridge and HomeKit/Siri.

I added the following to the config.json in Homebridge:-
  "platforms": [
    {
      "platform": "cmdSwitch2",
      "switches": [
        {
          "name": "Kettle",
          "on_cmd": "sudo python /home/andy/iBrew/ibrew start 192.168.1.52",
          "off_cmd": "sudo python /home/andy/iBrew/ibrew stop 192.168.1.52",
          "state_cmd": "sudo python /home/andy/iBrew/ibrew status 192.168.1.52"
        }
      ]
    
This works, however once the kettle has boiled the Kettle within HomeKit remains turned on.  Do you know if there is a way around this?

**Comment by Tristan79** [comment]
At the moment, no. But as I said, status is not working at the moment (to my big surprise), so that could be an issue. Sunday I have planned a test/fix bug session, and I am also going to try the homebridge myself. Will give you a notice here, what I found out :-)

**Comment by Tristan79** [comment]
Ok, fix bug in status, realised I need a short status, added a short status (so update your ibrew), installed ios 10 installed homebridge and its plugin cmdSwitch2 and added the following config, (see below): It seems to work perfectly... (well almost) i just heated some water and the status changed to off. 

The only thing that does not work is that the when the water is already at the temperature it... stays on until the home app updated the status... I wish I could push the info instead of homebridge pulling it... i have to look into that :-) 

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "iKettle Homebridge",

	"platforms": [{
		"platform": "cmdSwitch2",
		"switches": [{
			"name": "Kettle",
			"on_cmd": "/Users/Tristan/Coding/iBrew/ibrew start 10.0.0.99",
			"off_cmd": "/Users/Tristan/Coding/iBrew/ibrew stop 10.0.0.99",
			"state_cmd": "/Users/Tristan/Coding/iBrew/ibrew shortstatus 10.0.0.99 | grep 'heating'"
		}]

	}]
}

**Comment by Andybishop** [comment]
Thanks for the update, I updated iBrew (don't know if its the easiest way but I just dragged the new version over using WinSCP..) updated the config with the state_cmd as you detailed and it works great.  So does Homebridge/Homekit just poll for the update when the app is reopened?  I wonder if cmdswitch2 could be set to poll somehow.  I will look into this and let you know.  But this is great and thanks very much!!

**Comment by ozaoral** [comment]
Hi, first of all thanks a lot for the effort! Your tool made my HomeKit setup better than ever :) 

I was able to get it running on a Mac with Homebridge (had already working Nest connection). After some experiments I ended up with the config as @Andybishop 

		"platform": "cmdSwitch2",
        "switches": [{
            "name": "iKettle 2",
            "on_cmd": "python ~/.homebridge/iBrew/ibrew start 192.168.0.13",
            "off_cmd": "python ~/.homebridge/iBrew/ibrew stop 192.168.0.13",
            "state_cmd": "python ~/.homebridge/iBrew/ibrew shortstatus 192.168.0.13 | grep 'heating'"
        }]

(config based on your example did not work for me, but I am all but experienced in Python, so the problem might have been somewhere else ...)

I am able to turn the kettle on, off and when the water is boiling, the kettle turns off. Great so far. The Home app on iOS10 turns the kettle on and immediately shows the "!" noting loss of connection. So at the moment the kettle is boiling, Home app shows "off" and "no connection". Ability to turn off is a little unreliable (apparently works when the Home app is able to get the "on" status for a moment).

Even with this issue, the key feature for me works - ability to add "start" to the "good morning" HomeKit scene. So thanks again 👍

**Comment by Andybishop** [comment]
Mine works great with this configuration.  Have you tried running a ping to the IP address of the kettle incase it loses connection? I know the guy who spent 11 hours setting up his had this problem as the Kettle didn't have a static IP address.   Is it just the kettle that loses connection? Do you have any other devices setup, I have LightwaveRF light and power switches too.

**Comment by ozaoral** [comment]
That was one of the things I figured out during my 4 hours :) I reserved the IP for MAC address of the kettle. I have HomeKit native Elgato stuff (sensors as well as power outlets), Hue lights. I use Homebridge to link Nest, Nest Protect and iKettle. Homebridge is running on a Mac at this moment, I might be moving it to Pi in the future.

Based on the behaviour of other devices, I get a feeling that my Home app (few other HomeKit apps do the same) does not get an information back from the kettle that it has actually turned on.

**Comment by ozaoral** [comment]
Well I now found in the specs of cmdswitch 2 that error in the status call results in OFF notification to Homebridge. It led me to a logfile I found in Library/Application support/iBrew ....

2016-11-06 21:32:06,635 - DEBUG - [Errno 13] Permission denied: u'/Users/admin/Library/Application Support/iBrew/192.168.0.13.conf'
2016-11-06 21:32:06,635 - DEBUG - Traceback (most recent call last):
  File "/Users/admin/.homebridge/iBrew/smarter/SmarterInterface.py", line 48, in new
    r = fn(*args, **kwargs)
  File "/Users/admin/.homebridge/iBrew/smarter/SmarterInterface.py", line 1092, in disconnect
    self.__write_stats()
  File "/Users/admin/.homebridge/iBrew/smarter/SmarterInterface.py", line 53, in new
    raise e
IOError: [Errno 13] Permission denied: u'/Users/admin/Library/Application Support/iBrew/192.168.0.13.conf'
2016-11-06 21:32:06,635 - DEBUG - [Errno 13] Permission denied: u'/Users/admin/Library/Application Support/iBrew/192.168.0.13.conf'

Bingo ... iBrew returned error to cmdswitch 2 immediately upon turning the kettle on, because it could not write into the .conf file. Cmdswitch 2 in turn reported OFF to Homebridge (and the damage was done). So I fixed the permission and IT WORKS 💯 

Now I get status (immediately, not after few seconds as before), when the kettle turns on, it is correctly shown in the Home app as ON, I can turn it off during boiling.

**Comment by Andybishop** [comment]
Glad you got to the bottom of your issue and sounds like you have it working perfectly! I have mine running on a Ubuntu Virtual Machine.  Need to invest in some Nest products I think...

**Comment by Tristan79** [comment]
Domoticz is highly recommended if you want to bridge more different type of hardware (it also has a homebridge extension) also ibrew is born there as a script (it gotten a little out of hand, but I was sick lying in bed, had to do something :-). 

You should check it out: www.domoticz.com 

Static ip is recommended. And yes, the kettle and the smarter coffee do lose connection quite often if you run too many connections to it (like 2x smarter app open, and ibrew running). The chip inside is just not powerful enough to handle it (or crappy firmware :-). 

That why I created a relay mode. It emulates the kettle on your pc and have only one connection to the real kettle. And you can configure the smarter app to use that (or another ibrew). I really need to document stuff :-)

It also keeps stats about the usage of your kettle (or coffee machine) which I was planning to add as a nice graph in the web interface (which btw is just a replacement for the smarter app, why do they need to know when I brew my kettle?).  

If you remove the ip address it auto detects it (same mechanisme as the smarter app,`ibrew list` shows the ip addresses detected) but it adds two seconds. And if you have more then one device you still have to type it in (ibrew supports unlimited kettle and coffee machine :-) one kettle in the office, one kettle in the kitchen). 

![screen shot 2016-10-30 at 18 23 45](https://cloud.githubusercontent.com/assets/4981984/20044041/590dfebe-a495-11e6-8f5c-c4ee84794643.png)

![screen shot 2016-11-07 at 02 57 45](https://cloud.githubusercontent.com/assets/4981984/20044094/09d15cbe-a496-11e6-9588-640c91d1b6b2.png)

The permission denied error is strange... it writes the log file but not that? Bugs?! Bugs! Ow well this is what happens if you got very sick in the middle of coding session :-)

I did not expect anyone to use it, and it got over 250+ clones :-) Not bad for a side project to learn python (and other various IT techniques) while lying sick in bed. Of course the off-side is I can not change the names in the command line anymore :-)

Anyway. :-)

**Comment by ozaoral** [comment]
Hi @Tristan79, thanks for the demoticz info, I will check it out. The real use case for me is HomeKit, so I admit I have not used the nice interface ;)

**Comment by Tristan79** [comment]
HomeKit <-> Homebridge <-> Domoticz <-> various models of hardware sensors (zwave, 433, mysensors, and anything you script yourself like my denon stereo)

I tried many other software smart home controllers... but this stuck :-)

**Comment by Tristan79** [comment]
If anybody has an idea for the status update, event... post here

**Comment by Tristan79** [comment]
luisiam introduced **status polling** for the homebridge cmdswitch2 a couple of hours ago :-)
I am going to check it out tonight...

**Comment by ozaoral** [comment]
@Tristan79 wow, that is a GOOD news
my weekend project is migration of the HomeBridge setup to Raspberry Pi

**Comment by ozaoral** [comment]
@Tristan79 I was successful and have some more insights into possible homebridge issues. My migration to Raspberry Pi 3 went pretty well. I used the latest versions of iBrew and cmdSwitch2, everything works, including polling. I have just added the two lines into my config. Now when the water boils, the switch in homekit app goes to off. 
So far so good. But I found out that the fancy "let's type your name and email to agree with the license" file causes a lot of problems. It is necessary to run any iBrew command in terminal at least once. Agree with the license and only then the homebridge integration works. It also has to be done for all the users you want to run the homebridge. Therefore everything went well for me when I was starting homebridge under the default "pi" user. But then I created a new user "homebridge" to start homebridge automatically (based on the instruction in homebridge wiki) and it stopped working. Then I realised that the license has not been approved for that particular user and did it. And magically is works now in the ideal setup for - Raspberry Pi (no need to have the home Mac on), launches automatically.

**Comment by Tristan79** [comment]
Never thought about that, i only tested it under the user pi :-) Will make it that it runs anyway... easier then making you accept it for each user...  will do that when my new battery is delivered... machine died this morning :-/ can't do nothing on a dead dev machine :-) Meanwhile I will add a warning to the readme, i can manage that from my phone :-)

**Comment by Tristan79** [comment]
Thank!

**Comment by Tristan79** [comment]
Disabled the license check... i should really find out how processes run in deamon or other user modes... :-)

**Comment by Andybishop** [comment]
I've just tried to add the polling in for CMDSwitch2 but the config.json is causing homebridge to fail, what should this section look like in the config.json now?

**Comment by ozaoral** [comment]
Currently I have this working:

```
{
"platform": "cmdSwitch2",
"switches": 
[{
"name": "iKettle 2",
"on_cmd": "python /iBrew/ibrew start 192.168.0.13",
"off_cmd": "python /iBrew/ibrew stop 192.168.0.13",
"state_cmd": "python /iBrew/ibrew shortstatus 192.168.0.13 | grep 'heating'",
"polling": true,
"interval": 1
}]
}
```

**Comment by Andybishop** [comment]
Thats great thanks, for some reason it was not liking the shortstatus line that was already in there, removing it worked.  However re-entering it all is now working again.. very strange, but thanks it is working again now.

**Comment by JotWee** [comment]
just want to say THANK YOU to all contributors, you've done a great job!
