### ISSUE TITLE
Test mode? Simulate iKettle or Smarter Coffee!

### ISSUE THREAD

**Issue by bhaap** [Tristan79/iBrew#18]
Hi

I have ordered a Smarter Coffee machine but while I am waiting for it I thought I would setup iBrew with home assistant and test out if its working (aka showing stuff in the console. 

But it seems i am unable to start the program without a machine to connect to. 

Is there a way to run iBrew in test mode if you do not have your Smarter Coffee at hand?

**Comment by Tristan79** [comment]
Yep. I fixed some bugs (since relay is experimental, and i did not test all the console stuff), 
so you have to sync, download or clone it again.

use:
`./ibrew dump coffee relay out:COFFEE`

or

`./ibrew dump coffee relay out:GOD`

and in another terminal you can connect to it, like it was a normal smarter coffee machine. 

`./ibrew dump console 127.0.0.1`
`./ibrew start 127.0.0.1`
etc...

its experimental,... I did not implement like, actual simulation of a brew process... it just simulates the basic messages. (the firewall blocks messages (and thus simulates) with the group COFFEE,KETTLE,GOD,... )

Enjoy...

**Comment by bhaap** [comment]
Thank you! Will try it out this evening!

**Comment by bhaap** [comment]
I can atleast do "ibrew brew 4 35 beans strong 127.0.0.1" now and i dont get an error. But in the dump console of the relay i cannot see a reaction to my command. I can issue commands directly into the console and that works fine. But the reason i wanted to have the relay was to see if it reacted to my commands from home assistant.

Any ideas?

**Comment by Tristan79** [comment]
I did not implement a simulation. Is simulates static messages, will try to hack a sim in tonight :-) should not be much work. And then I can run it as a showcase website ;-) if I ever finish the web stuff...

**Comment by bhaap** [comment]
Nvm :D
I was running two instances of ibrew relay and was monotoring the one who did not get any messages. 

I now see some data when i send "brew" command.

`2016-11-12 17:49:12,425 - INFO - 192.168.1.117:46978 Client connected
2016-11-12 17:49:12,426 - INFO - 192.168.1.117:46978 Command message received relay [33] [Start coffee brewing] [33020223017e]
2016-11-12 17:49:12,427 - DEBUG - Blocked command: 33
[192.168.4.1:2016-11-12 17:49:12] Message Received [Command status] [03007e]
Command replied: success
2016-11-12 17:49:12,428 - INFO - 192.168.1.117:46978 relay send 03007e
2016-11-12 17:49:12,428 - INFO - 192.168.1.117:46978 client disconnected
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/johan/iBrew/smarter/SmarterInterface.py", line 556, in __serverMonitor
    clientsock.send(r)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor`

**Comment by bhaap** [comment]
Got the setup like this:

  - platform: command_line
    switches:
      2_koppar:
        command_on: "/usr/local/bin/ibrew brew 2 20 beans strong 127.0.0.1"
        command_off: "/usr/local/bin/ibrew stop 127.0.0.1"
        command_state : "/usr/local/bin/ibrew shortstatus 127.0.0.1 | grep 'brewing'"
        value_template: "brewing"
        friendly_name: "2 koppar kaffe"

And the error im getting is:

```
INFO:homeassistant.components.http:Serving /api/services/switch/turn_on to 127.0.0.1 (auth: True)
INFO:homeassistant.core:Bus:Handling <Event call_service[L]: service=turn_on, service_call_id=3048983120-3, domain=switch, service_data=entity_id=switch.2_koppar_kaffe>
INFO:homeassistant.components.switch.command_line:Running command: /usr/local/bin/ibrew brew 2 20 beans strong 127.0.0.1
Traceback (most recent call last):
  File "/usr/local/bin/ibrew", line 4, in <module>
    from iBrewConsole import *
  File "/home/johan/iBrew/iBrewConsole.py", line 17, in <module>
    from iBrewWeb import *
  File "/home/johan/iBrew/iBrewWeb.py", line 5, in <module>
    import tornado.escape
  File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 28, in <module>
    from tornado.util import PY3, unicode_type, basestring_type
  File "/usr/local/lib/python2.7/dist-packages/tornado/util.py", line 47, in <module>
    import typing  # noqa
  File "/home/johan/.local/lib/python3.4/site-packages/typing.py", line 103
    def __new__(cls, name, bases, namespace, *, _root=False):
                                              ^
SyntaxError: invalid syntax
```

Any ideas here?

**Comment by Tristan79** [comment]
i do not think you can run two relays on the same machine (ip address) at the moment since you can not change the 2081 port in any client (and i have not implemented that yet in ibrew, relay is new) and you can not have two running apps share the same port. if you run the two relays on separate (virtual) machines it should work...  

secondly you use python 3 or mix site packages from python 2 and 3? Seeing:

`/home/johan/.local/lib/python3.4/site-packages/`


It looks like a conflict between python 2 and 3...

try to run instead of /usr/local/bin/ibrew brew 2 20 beans strong 127.0.0.1
run it directly with the right python

`/location/python2xexecutable/python /locationof/iBrew/ibrew brew 2 20 beans strong 127.0.0.1`

if that  does not work... it is probably a path export setting pointing to python3 instead of 2... :-/

it is designed for python 2.7, i tried to run it in python 3 but the print alone (see branch) took me over an hour... and it is not working, i am no python 3 expert (and hardly a python 2) and the changed alot... :-/

**Comment by bhaap** [comment]
Its wierd. eventhou im trying to call the command via the python2.7 bin it still tries to use one python 3.4 module.... hmmm

http://pastebin.com/KpP0fg3L

**Comment by bhaap** [comment]
Nvm, im just porting home assistant to homebridge anyway so the working cmdswitch2 is the way to go i guess.

would have been nice to have all things in one place thou :P

**Comment by Tristan79** [comment]
I got the kettle simulated :-)

`./ibrew dump kettle relay out:god,in:14`

a couple more hours for the coffee machine ;-)

**Comment by bhaap** [comment]
Nice! :D Really good work on this addon :D Gonna get myself a kettle aswell just bacause of your work :D You should get a cut of the sales due to your code :D

**Comment by Tristan79** [comment]
Well Smarter, they do not respond to any email (I was hoping on the last protocol puzzle pieces), so any donation or cut from them... :-).  He smarter dudes! If you are reading, last puzzle pieces!

That what it is for me, a puzzle :-) Playing with different techniques... sailing unknown territories :D

It is a fun puzzle, decoding the protocol, playing with python, css,  javascript, coding techniques. It was because of my git server crashed that it ended up on github. Never thought is was going to be used :-)

Well you can alway donate a little cut to the iBrew "Support Crew" Piggy Bank! Currently saving for 

This I can not find a better one or they are way expensive co2 sensor
http://shop.vair-monitor.com/index.php?rt=product/product&path=71&product_id=133

And for my poor plants!
https://www.aliexpress.com/item/Original-Xiaomi-Mi-Flora-Monitor-Digital-Plants-Grass-Flowers-Soil-Water-Light-Smart-Tester-Sensor-for/32756299881.html

Luckily somebody already decoded the protocol ;-) But I feel a **_iGrew_** coming... probably not as
elaborate as this :D, I think I will reuse parts of the code of the json rest api and web pages,  add a command line and add triggers (which are coming very soon for ibrew: triggers: on receiving status updates it opens an url or run a script when things change) but no fancy simulation, relays, firewall or debugging modes... :D

https://www.open-homeautomation.com/2016/08/23/reverse-engineering-the-mi-plant-sensor/

:-)

**Comment by Tristan79** [comment]
`./ibrew dump coffee relay out:god,in:32`

works, but missing carafe removal and filling the water supply simulation events and
there is a bug in waterlevel... so you still can make more then 12 cups ;-) 
But that minor thing has no importance, cuz rest is fully functional.

But I have enough for a day or two ;-) 

Probably not wholly accurate simulation :-) of the coffee machine, but good enough for testing. It grinds, it brews, it keeps the carafe warm and mimics the coffee machine enough that it fools the smarter app or ibrew itself.

Enjoy :-D

**Comment by bhaap** [comment]
Gonna try it out this evening :)

**Comment by Tristan79** [comment]
Just you know! luisiam introduced **status polling** for the homebridge cmdswitch2 a couple of hours ago :-) This means hopefully a correct status in homekit. I am going to check it out tonight...

**Comment by bhaap** [comment]
Im getting alot of Python error messages when trying to simulate the coffee. No crash but just alot of errors in the middle of all normal messages. 

Also brewing stops after 8ish messages and just stays there. Is that normal?

**Comment by bhaap** [comment]
Yeah I saw the polling thats awesome!

Btw. Is there any way to get more time on the hotplate?

**Comment by Tristan79** [comment]
Hacked code... ;-)

When I wrote it, I speeded up the brewing, so its probably faster (max +/-10 seconds depending on the amount of cups)...

I also notice the smarter app does not want to connect to it... Bugs ;-)
I still have a lot of testing to do...

Could you post the error messages (well and all the text surround it, context :-)
Then I know where to search...

Well, the simulation was not planned (that why the hack)... But I was going to write an event trigger system which can execute url or script files on events like brew finished, hotplate finished... (and every status update)... such that you can push values and events to (a lot) of smart home controllers.

Since that was my original goal to begin with... (all the rest is just me playing, passing the time, while I am lying sick in bed, it beats seeing movie or reading book number 1001 :-)

I probably can make it that if you use a relay, it keeps the hotplate on for much longer (switching it back on again when it switches off...)

Late december I was planning (but it could be later, I got really sick so that why its called ibrew intermezzo) to combine the webserver (and finish it) with the relay server. Such that you can run it as a complete bridge... (have rest api, web interface and I will try to combine the ikettle and the coffee machine on default port, but also for each device relayes on a seperate port 2082++  such that you still can use the ibrew command line interface or homebridge with it... 

Such that it keeps stats, connect it to your favourite smart home controller, you can patch messages or events... I will keep the patch of longer hotplate in mind...

I will look into the sim tomorrow, could not test all and it should connect with the smarter app. But please post the error... ;-)

**Comment by Tristan79** [comment]
I think I found out why you got error messages, there probably socket error which I should handle more  elegantly... but are still displayed for debugging mode... will we fixed later :-)

**Comment by Tristan79** [comment]
i fixed the brewing/grinding grep which was not working on some platforms, you now can grep busy instead of the brewing/grinding combo ;-)
see frontpage :-)

**Comment by bhaap** [comment]
Thank you!

**Comment by Tristan79** [comment]
Yes there is, it can be turn on when it turns off for a extended period of time,... should be a part of the "patch" system. But its not implemented ;-) Like the grind only function, and other stuff (like timers events)...  or the "gready beans protection" patch which blocks all beans request and stops the coffee machine when it begins to grind (and switch to filter?)... nice in combination with geolocation ;-) No bean coffee when you are away ;-)

**iBrew with  "gready beans protection"**
_We know, your beans are precious_

After the firewall, simulator and now be able to run scripts or fire an url with the new event trigger system ;-) all the pieces are there for the patch system. 

I am going to fiddle with either that or the webpages ;-) ...or why it does not quit most of the time... usually programs crash and quits, this one does not want to quit...

also going to combine the web server with the event trigger system and the relay server... such that you only have to run one app for all things...   also trying to combine a kettle and a coffee machine on relay one port such that the app can use both...   enough to play with ;-)

**Comment by bhaap** [comment]
Haha you have your work setup for you, glhf! Appairently there is hard to get a smarter coffee in where i am, all the resellers are out of stock. So have not been able to get my hands on one yet :(

**Comment by Tristan79** [comment]
How long do you think is an appropiate time for the maximum hotplate? always on? 2 hours?

**Comment by bhaap** [comment]
Well I like the fact to be able to set the time but maximum maby 60minutes? After that the coffee starts tasting shit anyway :P
