### ISSUE TITLE
Turn the boiler on and setting the temperature?

### ISSUE THREAD

**Issue by Moskus** [Tristan79/iBrew#3]
I can turn the boiler on, but I can't set the temperature.
`0x15 [temp] 0x7E`
... should do the trick, but it doesn't.

What are you using (I see there are multiple commands)?

**Comment by Moskus** [comment]
... this is with the v19 firmware.

**Comment by Tristan79** [comment]
I put the protocol on the front page, so its not hidden...

Command 15 had two mandatory arguments. So it will fail if you forgot one...  you can send 
a keepwarm time of 0 minutes...

```
Command Message 15: Heat kettle
Argument: <TEMPERATURE><KEEPWARMTIME>
Example: 15 32 00 7e

```

I am still figuring out the rest of the boil commands, (there are 6 different commands to boil the water, some ignore the default settings, some don't, some I still have to try. But it's a slow process and I wait until I want some tea to check a state :-) 

Anyway the app uses command 21. Not sure about the parameters. Did not wireshark everything yet, will update the protocol if I find out more!. Or share your results..

**Comment by Moskus** [comment]
Thank you very much!!!
I didn't realize the keep warm time was mandatory, even if it was 0.

I get the same results with 15 and 21. Don't know why.

I'm only borrowing the boiler to write a plugin for HomeSeer, but I do have the Coffee Machine. I'll send you the commands I use for it (need to do some Wiresharking too after the new firmware got released).

**Comment by Tristan79** [comment]
Probably because the default settings on the kettle itself is still 100 degrees C. 
Check out the command: 2e 7e get user defaults which results in something like this:

[2f _50 07_ 01 7e 00 03 00 7e]

Boil water to 80ºC (0x50),  and keep it warm for 7 minutes.  not sure about the rest... 
you can set user settings with 0x1f btw... 

Also Command 20 ignores any user settings on the kettle and boils to 100 (not sure about warm time) etc... still some figuring out to do. 

Anway, you can use the dump command of iBrew to see all messages and play around with your device.. I hope it works for the coffee machine!

./iBrew dump console 192.168.4.1

If you could try to run the sweep command ( ./iBrew sweep ip
) for the coffee machine (if its working), it maps out all commands available by looking at the responses e.g. 03 69 7e no command, anything else yeah a new command (or reply)! Not all commands can be discovered by wireshark.
 
I will update the protocol tonight with some extra stuff I found. 

Also note that I add an auto detect feature yesterday, you probably want to copy/use that in your homeseer plugin so users to not have to fill in any ip addresses or hostname....  it should detect more then one device, but I only tested it with one ;-)

./iBrew list

You should look in the smarterclient code (currently at line 120) for:

def find_devices(self):

it's around 20 lines of code which would make your users life that much easier :-)

**Comment by Moskus** [comment]
Oh how much I wish that you had the Anova "Precision Cooker" Sous Vide device! ;-)

**Comment by Tristan79** [comment]
That one, it's cloud based... probably means all traffic is https encrypted if it uses wifi.
If it's bluetooth you can probably sniff it....

http://community.anovaculinary.com/discussion/1791/can-anyone-point-me-to-the-bluetooth-communication-and-command-protocol-for-the-precitison-cooker

**Comment by Moskus** [comment]
Yes, the Anova Wifi cooker uses the amazon cloud. I was hoping for a local connection too easier for sniffing, but alas, no such luck. At least not yet.

With bluetooth we can use pycirculate:
https://github.com/erikcw/pycirculate

... but it feels rather stupid to have to control it via a RPi. Apparently the official API was due to be released in "a couple of months", but that was 3 months ago. When asked now, they don't have it on their imediate timeline.

... but we're getting off topic. ;)

**Comment by Tristan79** [comment]
You could hope, (i seen it happen on those little wifi devices) that it does not check if its getting a valid certificate. Using a man in the middle proxy...

Read the yellow boxes! From:

http://security.stackexchange.com/questions/8145/does-https-prevent-man-in-the-middle-attacks-by-proxy-server#4

**Comment by Tristan79** [comment]
I build a rest api (almost done) for it and a web interface (just started)... found out almost all coffee codes, so stay tuned! Still alpha!
