### ISSUE TITLE
iBrew slow to return?

### ISSUE THREAD

**Issue by LeeUK** [Tristan79/iBrew#4]
Great bit of Python, thank you. 

I haven't tried it on another platform yet, but my "dev" box takes approximately 12s per iteration of iBrew to return any output. Is this normal? I haven't had time to do much digging yet.

**Comment by Tristan79** [comment]
Slow mode is what you are getting at the moment...  I build the console for debug first, and now that it is working, I am gradually transforming it to a command line and domoticz bridge, (feel free to add your favorite smarthome controller code) that means some stuff when run from the command line does not have to happen.

i am working on the commands and speed! in the upcoming version (e.t.a. 1 day, still testing almost done) you have shout mode and go mode...

Fastest:   shout mode send a command without waiting for any reply. (~1/9 time)
Fast:        go mode skips first checking if it's the right device or getting base values (~1/3 the time).
Normal:   check if device is correct this is around ~3 seconds, it will go down, since I have other ways to detect which device instead of sending a command.
Slow:       full mode initialize default value's (use in monitor, domoticz, sweep and console) (3x the time)

you can see what it doing (in the 12s) by running 
./iBrew dump info 192,...

and if one device is present it will (try) to auto-detect it if you enter no host, thus by entering an host it skips this (-0.5 seconds).

I have to fiddle around with the network code, it can be a bit faster, I probably should have solved that at the beginning. But this is all this is new for me :-)

For now I want to finish the command code, (such as heat, brew with arguments) and add the new messages.

You probably have a kettle, but if you do have the coffee, I do not have a smarter coffee, but i will test most of it anyway (sending the command, the kettle just does not respons well)... but I can not check the responses. and I will make typing errors :-)

:-)

**Comment by LeeUK** [comment]
Hey Tristan!

Great to hear iBrew is working as expected, I had a horrible feeling it was my environment for a minute. I shall await the faster version ;) 

'Shout' mode sounds really good, and 'fastest' would be good for everything else (for me, at least). The missus won't use anything I create when the 'real' app is faster lol. 

Like you I only have the iKettle; The coffee machine may have to wait a while. I don't use an off-the-shelf home automation system, it's (pardon the pun) home-brewed and cobbled together across multiple systems and platforms, with one consistent mobile and watch (Pebble) interface. 

Great work, and I'll contribute where I can! :)

**Comment by Tristan79** [comment]
It still unfinished, and I have to fix a lot :-) but you can check out the new code... 

./iBrew shout on 10.0.0.99

it also got a rest api. but there is still alot unfinished at the moment, I am building as I go... so check back in some time.

**Comment by Tristan79** [comment]
The command line code is finally ready... (at least minus the occasional bug).
Working on a web interface :-)
